### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by landgenoot** [leogodoyllg/News-Website-Template#1]
I would like to use your template for a prototype which is part of my thesis at the Technical University of Berlin. Unfortunately, this repository is unlicensed.

Do you mind if I use it for academic purposes?

**Comment by landgenoot** [comment]
I looks like this repo is forked from:
https://github.com/imshashikantdev/WTFNews
Which has a MIT license, so I can use that one.

Thanks anyway!

**Comment by shashikantdev3** [comment]
> I would like to use your template for a prototype which is part of my thesis at the Technical University of Berlin. Unfortunately, this repository is unlicensed.
> 
> Do you mind if I use it for academic purposes?

@landgenoot, for sure you can use my template for your thesis.
